// app/violin-exam/free-downloads/pdfItems.ts

export type PdfCategory = "note" | "music" | "planner" | "learning";

export type PdfItem = {
  id: number;
  fileName: string;      // 拡張子なしのファイル名 (例: "Note-Blank-Fancy-A4L")
  title: string;         // 英語タイトル（サイト表示）
  titleJa: string;       // 日本語タイトル（補足用・hoverや説明用）
  category: PdfCategory; // Note / Music / Planner / Learning
  size: "A4縦" | "A4横";
  series: "Fancy";       // 将来 Simple / Plain / Choco など増やせる
  tags?: string[];       // 検索用タグ
};

// ★ まずは代表的なものだけ入れておいて、あとで増やすでもOK
export const pdfItems: PdfItem[] = [
  // --- Note (901–908) ---
  {
    id: 901,
    fileName: "Note-Blank-Fancy-A4L",
    title: "Blank Note (Portrait)",
    titleJa: "無地ノート（縦）",
    category: "note",
    size: "A4縦",
    series: "Fancy",
    tags: ["note", "blank", "portrait"],
  },
  {
    id: 902,
    fileName: "Note-RuledW-Fancy-A4L",
    title: "Ruled Note – Wide (Portrait)",
    titleJa: "横罫ノート（縦）",
    category: "note",
    size: "A4縦",
    series: "Fancy",
    tags: ["note", "ruled", "portrait"],
  },
  {
    id: 903,
    fileName: "Note-RuledL-Fancy-A4L",
    title: "Ruled Note – Narrow (Portrait)",
    titleJa: "縦罫ノート（縦）",
    category: "note",
    size: "A4縦",
    series: "Fancy",
    tags: ["note", "ruled", "portrait"],
  },
  {
    id: 904,
    fileName: "Note-Grid-Fancy-A4L",
    title: "Grid Note (Portrait)",
    titleJa: "方眼ノート（縦）",
    category: "note",
    size: "A4縦",
    series: "Fancy",
    tags: ["note", "grid", "portrait"],
  },
  {
    id: 905,
    fileName: "Note-Blank-Fancy-A4W",
    title: "Blank Note (Landscape)",
    titleJa: "無地ノート（横）",
    category: "note",
    size: "A4横",
    series: "Fancy",
    tags: ["note", "blank", "landscape"],
  },
  {
    id: 906,
    fileName: "Note-RuledW-Fancy-A4W",
    title: "Ruled Note – Wide (Landscape)",
    titleJa: "横罫ノート（横）",
    category: "note",
    size: "A4横",
    series: "Fancy",
    tags: ["note", "ruled", "landscape"],
  },
  {
    id: 907,
    fileName: "Note-RuledL-Fancy-A4W",
    title: "Ruled Note – Narrow (Landscape)",
    titleJa: "縦罫ノート（横）",
    category: "note",
    size: "A4横",
    series: "Fancy",
    tags: ["note", "ruled", "landscape"],
  },
  {
    id: 908,
    fileName: "Note-Grid-Fancy-A4W",
    title: "Grid Note (Landscape)",
    titleJa: "方眼ノート（横）",
    category: "note",
    size: "A4横",
    series: "Fancy",
    tags: ["note", "grid", "landscape"],
  },

  // --- Music (101–111) ---
  {
    id: 101,
    fileName: "Music-Staff-Wide-Fancy-A4L",
    title: "Staff Paper – Wide",
    titleJa: "五線譜（広め）",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "staff", "wide"],
  },
  {
    id: 102,
    fileName: "Music-Staff-Narrow-Fancy-A4L",
    title: "Staff Paper – Narrow",
    titleJa: "五線譜（狭め）",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "staff", "narrow"],
  },
  {
    id: 103,
    fileName: "Music-NotePractice-Fancy-A4L",
    title: "Note Practice Sheet",
    titleJa: "音符練習シート",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "notes", "practice"],
  },
  {
    id: 104,
    fileName: "Music-Alphabet-8notes-Fancy-A4L",
    title: "Alphabet Practice (8 Notes)",
    titleJa: "アルファベット練習（8音）",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "alphabet", "practice"],
  },
  {
    id: 105,
    fileName: "Music-Katakana-8notes-Fancy-A4L",
    title: "Katakana Practice (8 Notes)",
    titleJa: "カタカナ練習（8音）",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "katakana", "practice"],
  },
  {
    id: 106,
    fileName: "Music-StaffSplit-GridBottom-Fancy-A4L",
    title: "Staff + Grid (Bottom)",
    titleJa: "上部五線譜・下部方眼",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "staff", "grid"],
  },
  {
    id: 107,
    fileName: "Music-StaffSplit-StaffBottom-Fancy-A4L",
    title: "Staff + Staff (Bottom)",
    titleJa: "上部五線譜・下部五線譜",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "staff", "double"],
  },
  {
    id: 108,
    fileName: "Music-LessonNote-Fancy-A4L",
    title: "Lesson Note",
    titleJa: "レッスンノート",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "lesson", "note"],
  },
  {
    id: 109,
    fileName: "Music-LessonNoteKana-Fancy-A4L",
    title: "Lesson Note (Kana)",
    titleJa: "レッスンノート（ひらがな）",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "lesson", "kana"],
  },
  {
    id: 110,
    fileName: "Music-WeeklyPracticeLog-Fancy-A4L",
    title: "Weekly Violin Practice Log",
    titleJa: "WeeklyViolinPracticeLog",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "practice", "violin", "weekly"],
  },
  {
    id: 111,
    fileName: "Music-Repertoire-Fancy-A4L",
    title: "Repertoire List",
    titleJa: "Repertoire",
    category: "music",
    size: "A4縦",
    series: "Fancy",
    tags: ["music", "repertoire"],
  },

  // --- Planner / P- (201–212) ---
  {
    id: 201,
    fileName: "P-MonthlyGoals-Fancy-A4L",
    title: "Monthly Goals",
    titleJa: "MonthlyGoals",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "goals", "monthly"],
  },
  {
    id: 202,
    fileName: "P-MonthlyWeeklyGoals-Fancy-A4L",
    title: "Monthly & Weekly Goals",
    titleJa: "Monthly/WeeklyGoals",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "goals", "weekly"],
  },
  {
    id: 203,
    fileName: "P-ToDoList-Fancy-A4L",
    title: "To-Do List",
    titleJa: "ToDoList",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "todo"],
  },
  {
    id: 204,
    fileName: "P-Timetable-Fancy-A4L",
    title: "Timetable",
    titleJa: "Timetable",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "timetable", "schedule"],
  },
  {
    id: 205,
    fileName: "P-YearlyCalendar-Mon-Fancy-A4L",
    title: "Yearly Calendar (Mon Start)",
    titleJa: "年間カレンダー（月曜はじまり）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "yearly"],
  },
  {
    id: 206,
    fileName: "P-YearlyCalendar-Sun-Fancy-A4L",
    title: "Yearly Calendar (Sun Start)",
    titleJa: "年間カレンダー（日曜はじまり）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "yearly"],
  },
  {
    id: 207,
    fileName: "P-MonthlyCalendar-Mon-Fancy-A4L",
    title: "Monthly Calendar (Mon Start)",
    titleJa: "月間カレンダー（月曜はじまり）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "monthly"],
  },
  {
    id: 208,
    fileName: "P-MonthlyCalendar-Sun-Fancy-A4L",
    title: "Monthly Calendar (Sun Start)",
    titleJa: "月間カレンダー（日曜はじまり）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "monthly"],
  },
  {
    id: 209,
    fileName: "P-WeeklyCalendar-Mon-Fancy-A4L",
    title: "Weekly Calendar (Mon Start)",
    titleJa: "週間カレンダー（月曜はじまり）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "weekly"],
  },
  {
    id: 210,
    fileName: "P-WeeklyCalendar-Sun-Fancy-A4L",
    title: "Weekly Calendar (Sun Start)",
    titleJa: "週間カレンダー（日曜はじまり）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "weekly"],
  },
  {
    id: 211,
    fileName: "P-YearlyCalendar-Sun-Fancy-A4L-2026",
    title: "Yearly Calendar 2026 (Sun Start)",
    titleJa: "年間カレンダー（日曜はじまり 2026）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "yearly", "2026"],
  },
  {
    id: 212,
    fileName: "P-MonthlyCalendar-Sun-Fancy-A4L-2026",
    title: "Monthly Calendar 2026 (Sun Start)",
    titleJa: "月間カレンダー（日曜はじまり 2026/1）",
    category: "planner",
    size: "A4縦",
    series: "Fancy",
    tags: ["planner", "calendar", "monthly", "2026"],
  },

  // --- Learning (301–306) ---
  {
    id: 301,
    fileName: "Learning-StampBook-Fancy-A4W",
    title: "Stamp Book",
    titleJa: "StampBook",
    category: "learning",
    size: "A4横",
    series: "Fancy",
    tags: ["learning", "stamp"],
  },
  {
    id: 302,
    fileName: "Learning-Alphabet-Uppercase-Fancy-A4W",
    title: "Alphabet Practice – Uppercase",
    titleJa: "Alphabet Practice（大文字）",
    category: "learning",
    size: "A4横",
    series: "Fancy",
    tags: ["learning", "alphabet", "uppercase"],
  },
  {
    id: 303,
    fileName: "Learning-Alphabet-Lowercase-Fancy-A4W",
    title: "Alphabet Practice – Lowercase",
    titleJa: "Alphabet Practice（小文字）",
    category: "learning",
    size: "A4横",
    series: "Fancy",
    tags: ["learning", "alphabet", "lowercase"],
  },
  {
    id: 304,
    fileName: "Learning-Numbers-Fancy-A4W",
    title: "Numbers Practice",
    titleJa: "Numbers Practice",
    category: "learning",
    size: "A4横",
    series: "Fancy",
    tags: ["learning", "numbers"],
  },
  {
    id: 305,
    fileName: "Learning-Hiragana-Fancy-A4W",
    title: "Hiragana Practice",
    titleJa: "ひらがな練習",
    category: "learning",
    size: "A4横",
    series: "Fancy",
    tags: ["learning", "hiragana"],
  },
  {
    id: 306,
    fileName: "Learning-Katakana-Fancy-A4W",
    title: "Katakana Practice",
    titleJa: "カタカナ練習",
    category: "learning",
    size: "A4横",
    series: "Fancy",
    tags: ["learning", "katakana"],
  },
];
